spring:
  config:
    import:
      - classpath:mysql-prod.yml
      - classpath:mongo-prod.yml
      - classpath:redis-prod.yml
      - classpath:kafka-prod.yml
  
  # P6Spy Configuration for Prod
  decorator:
    datasource:
      enabled: true
      p6spy:
        enable-logging: true
        logging: none
        log-filter:
          pattern: .*
  
  jpa:
    properties:
      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 0 # Disable Hibernate slow query log in favor of P6Spy
  logging:
    level:
      org.hibernate.SQL: OFF
      org.hibernate.SQL_SLOW: OFF # We leverage P6Spy for slow queries
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
            apple:
              client-id: ${APPLE_CLIENT_ID}
              client-secret: ${APPLE_CLIENT_SECRET}
  jwt:
    secret: ${JWT_SECRET_KEY} # Managed by GitHub Secrets / Environment Variables
    expiration: 3600000 # 1 hour
    refresh-expiration: 1209600000 # 14 days

# Swagger Configuration - Production Environment
swagger:
  enabled: false  # Explicitly disabled in production
