port 26379
dir /tmp
sentinel resolve-hostnames yes
sentinel monitor redis-sentinel redis-master 6379 2
sentinel down-after-milliseconds redis-sentinel 5000
sentinel parallel-syncs redis-sentinel 1
sentinel failover-timeout redis-sentinel 60000