name: langlez-kafka-cluster

networks:
  langlez-net:
    driver: bridge

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "9000:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: langlez-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - langlez-net

  kafka-1:
    container_name: langlez-kafka-1
    image: confluentinc/cp-kafka:7.9.0
    hostname: kafka-1
    restart: on-failure
    ports:
      - "9001:9094"
    volumes:
      - ./volume/kafka/1:/var/lib/kafka/data
    env_file:
      - ./config/kafka/kafka.env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,CONTROLLER://kafka-1:29093,EXTERNAL://localhost:9001
    networks:
      - langlez-net

  kafka-2:
    container_name: langlez-kafka-2
    hostname: kafka-2
    image: confluentinc/cp-kafka:7.9.0
    restart: on-failure
    ports:
      - "9002:9094"
    volumes:
      - ./volume/kafka/2:/var/lib/kafka/data
    env_file:
      - ./config/kafka/kafka.env
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,CONTROLLER://kafka-2:29093,EXTERNAL://localhost:9002
    networks:
      - langlez-net

  kafka-3:
    container_name: langlez-kafka-3
    hostname: kafka-3
    image: confluentinc/cp-kafka:7.9.0
    restart: on-failure
    ports:
      - "9003:9094"
    volumes:
      - ./volume/kafka/3:/var/lib/kafka/data
    env_file:
      - ./config/kafka/kafka.env
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,CONTROLLER://kafka-3:29093,EXTERNAL://localhost:9003
    networks:
      - langlez-net