name: langlez-gateway

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: langlez-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - langlez-net

networks:
  langlez-net:
    name: langlez-net
    driver: bridge
