-- relationship 모듈을 follow / block / report 로 나누면서 아웃박스도 모듈별로 쪼갠다.
--
-- V12 가 아니라 V13 이다. 처음엔 V12 로 썼는데 그 사이 V12__notification_settings 가 머지됐다.
-- 같은 번호가 둘이면 Flyway 가 기동에서 죽는다. 이미 적용된 쪽을 건드리지 않고 이쪽을 밀었다.
-- 이 저장소 관례가 모듈당 아웃박스다 (member_event_outbox, chat_event_outbox, echo_event_outbox).
--
-- report 는 발행하는 이벤트가 없어 아웃박스를 만들지 않는다.
--
-- member_follows / member_blocks / reports 테이블은 건드리지 않는다. 엔티티가 어느 모듈에 있든
-- @Table(name = ...) 로 같은 테이블을 가리키면 되고, 이름을 바꾸면 데이터 마이그레이션이 따라붙는다.
-- V6 의 팔로우 인덱스와 V7 의 신고 유니크 제약도 그대로 산다.
--
-- 새 테이블은 relationship_event_outbox 와 완전히 같은 구조다 (infra:rdb 의 OutBox / OutBoxHistory
-- 베이스를 그대로 쓰므로 컬럼이 갈릴 수 없다).
--
-- 인덱스는 concurrently 를 쓰지 않는다. 방금 만든 빈 테이블에 거는 것이라 락이 0초다.
-- 근거 전문은 V8 주석에 있다.

create table follow_event_outbox (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table follow_event_outbox_history (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    id bigint not null,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table block_event_outbox (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table block_event_outbox_history (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    id bigint not null,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

-- 기존 행을 옮긴다. **여기를 빼고 옛 테이블을 drop 하면 아직 발행되지 않은 이벤트가 통째로 사라진다.**
--
-- 이 아웃박스로 나가는 이벤트는 member-followed 하나뿐이다 (RelationshipEventListener 가 유일한
-- 기록 지점이었고 topic 이 리터럴 하나였다). 그래서 전량을 follow 쪽으로 옮긴다.
-- block_event_outbox 는 새 이벤트라 옮길 행이 없다.
--
-- select * 를 쓰지 않는다. 컬럼 순서가 어긋나면 조용히 엉뚱한 값이 들어간다.
--
-- id 를 그대로 옮긴다. history 는 원본 id 를 복사하는 구조라(OutBoxHistory) 재채번하면
-- 원본과의 대응이 끊긴다. 옮긴 뒤 identity 시퀀스를 최대 id 다음으로 올려 PK 충돌을 막는다.
insert into follow_event_outbox
    (id, domain, topic, payload, "key", tries, status, created_at, completed_at, failed_at)
select id, domain, topic, payload, "key", tries, status, created_at, completed_at, failed_at
  from relationship_event_outbox;

insert into follow_event_outbox_history
    (id, domain, topic, payload, "key", tries, status, created_at, completed_at)
select id, domain, topic, payload, "key", tries, status, created_at, completed_at
  from relationship_event_outbox_history;

-- 위 insert 가 id 를 명시로 넣었으므로 identity 시퀀스는 아직 1이다. 그대로 두면 다음 insert 가
-- 기존 id 와 충돌한다. 양쪽이 다 비었으면 1로 둔다.
--
-- **history 의 max 도 같이 본다.** history 는 원본 아웃박스 행의 id 를 PK 로 재사용하고
-- (OutBoxHistory(o: OutBox) 가 id = o.id 다), 아카이빙이 원본 행을 deleteAllInBatch 로 지운다.
-- 그래서 이 마이그레이션 시점에 원본은 비어 있고 history 에만 id 1..N 이 쌓여 있는 게 정상이다.
-- 원본만 보고 시퀀스를 1로 되돌리면 신규 팔로우가 id 1,2,3 으로 채번되고, 다음 아카이빙에서
-- history PK 와 충돌해 배치가 매일 롤백된다 — 아웃박스가 영영 안 비워진다.
select setval(
    pg_get_serial_sequence('follow_event_outbox', 'id'),
    greatest(
        coalesce((select max(id) from follow_event_outbox), 0),
        coalesce((select max(id) from follow_event_outbox_history), 0)
    ) + 1,
    false
);

-- block 쪽은 setval 이 필요 없다. 두 테이블 다 위에서 방금 만든 빈 테이블이고 옮겨 오는 행이
-- 없어서(member-blocked 는 이 PR 에서 처음 생긴 이벤트다) 시퀀스 1 이 곧 정답이다.

drop table relationship_event_outbox;
drop table relationship_event_outbox_history;

-- V8 이 relationship_event_outbox_history 에 걸어 둔 보존 기간 정리용 인덱스를 새 테이블에 다시 만든다.
-- 없으면 매일 도는 "created_at < cutoff" 정리 배치가 테이블을 통째로 순회한다.
create index IDX_FOLLOW_OUTBOX_CREATED_AT
   on follow_event_outbox_history (created_at);

create index IDX_BLOCK_OUTBOX_CREATED_AT
   on block_event_outbox_history (created_at);

-- V1 의 IDX_RELATIONSHIP_OUTBOX_DOMAIN 대응. 엔티티(@Index)에도 같은 이름으로 선언돼 있다.
create index IDX_FOLLOW_OUTBOX_DOMAIN
   on follow_event_outbox_history (domain);

create index IDX_BLOCK_OUTBOX_DOMAIN
   on block_event_outbox_history (domain);
