-- 언어 프로필. 이 앱은 언어교환인데 "내가 하는 언어 / 배우는 언어"를 담을 자리가 없었다.
-- member_profiles.language_level 은 레벨만 있고 **어떤 언어의 레벨인지가 없어서** 매칭 입력이 되지 못한다.
--
-- member_id 는 members(id) 를 가리키지만 물리적 FK 는 걸지 않는다.
-- 다른 모듈 테이블을 참조하지 않는 규약(member_profiles·notification_settings 와 같다)을 따른다.
create table member_languages (
    id         bigint generated by default as identity,
    member_id  bigint       not null,
    -- BCP-47. check 제약으로 값을 묶지 않는다 — 지원 언어가 늘 때 마이그레이션 없이
    -- MemberLanguage.SUPPORTED 상수만 고치면 되게 한다.
    language   varchar(10)  not null,
    role       varchar(255) not null,
    level      varchar(255),
    created_at timestamp(6) with time zone not null,
    primary key (id),
    -- (member_id, language, role) 이 아니라 (member_id, language) 다. role 을 키에 넣으면
    -- 같은 언어를 모국어이자 학습언어로 동시에 등록할 수 있고, 그러면 매칭에서
    -- 자기 자신과 상호보완이 성립한다.
    constraint UNQ_MEMBER_LANGUAGE unique (member_id, language)
);

-- 상호보완 후보 질의(LanguageReader.complementaryCandidates)의 바깥쪽 스캔이 타는 인덱스다.
-- 안쪽(회원별 언어 확인)은 UNQ_MEMBER_LANGUAGE 선두 컬럼이 커버한다.
--
-- concurrently 를 쓰지 않는다. 방금 만든 빈 테이블이라 SHARE 락이 0초고,
-- concurrently 는 열려 있는 트랜잭션을 무한정 기다려 통합테스트를 세운 전력이 있다.
create index IDX_MEMBER_LANGUAGE_MATCH
    on member_languages (language, role, level);

-- 기존 값은 이관하지 않는다. 어떤 언어의 레벨인지가 애초에 기록돼 있지 않아
-- member_languages 의 (language, role, level) 로 복원할 방법이 없다. 사용자에게 다시 받는다.
alter table member_profiles
    drop column language_level;
