-- V1: 최초 스키마 베이스라인
--
-- 현재 JPA 엔티티에서 Hibernate 가 생성한 DDL 을 정리한 것이다.
-- 이후 스키마 변경은 이 파일을 고치지 말고 V2, V3... 을 새로 추가한다.
-- (이미 적용된 마이그레이션을 수정하면 체크섬이 어긋나 애플리케이션이 뜨지 않는다)

create table attachments (
    attached_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    uploader_id bigint not null,
    key varchar(1000),
    source varchar(255),
    source_id varchar(255),
    status varchar(255) check (status in ('PENDING','ATTACHED','DELETED')),
    type varchar(255) check (type in ('IMAGE','VIDEO','AUDIO')),
    primary key (id),
    constraint UNQ_ATTACHMENT_KEY unique (key)
);

create table chat_event_outbox (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table chat_event_outbox_history (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    id bigint not null,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table comments (
    author_id bigint not null,
    created_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    post_id bigint not null,
    content TEXT not null,
    primary key (id)
);

create table echo_event_outbox (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table echo_event_outbox_history (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    id bigint not null,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table hashtag_daily_stat (
    stat_date date not null,
    id bigint generated by default as identity,
    post_count bigint not null,
    search_count bigint not null,
    hashtag varchar(255) not null,
    primary key (id),
    constraint UNQ_HASHTAG_DAILY_STAT unique (hashtag, stat_date)
);

create table hashtags (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id),
    constraint UNQ_HASHTAG_NAME unique (name)
);

create table member_audits (
    agreed_terms_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    last_accessed_at timestamp(6) with time zone,
    last_handle_updated_at timestamp(6) with time zone,
    suspended_at timestamp(6) with time zone,
    verified_at timestamp(6) with time zone,
    withdrawn_at timestamp(6) with time zone,
    last_accessed_ip varchar(255),
    last_device_id varchar(255),
    primary key (id)
);

create table member_blocks (
    blocked_id bigint,
    blocker_id bigint,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    primary key (id),
    constraint UNQ_MEMBER_BLOCK unique (blocker_id, blocked_id)
);

create table member_event_outbox (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table member_follows (
    created_at timestamp(6) with time zone,
    followed_id bigint,
    follower_id bigint,
    id bigint generated by default as identity,
    primary key (id),
    constraint UNQ_MEMBER_FOLLOW unique (follower_id, followed_id)
);

create table member_image_urls (
    represent boolean not null,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    file_size bigint not null,
    id bigint not null,
    sequence bigint not null,
    url varchar(255) not null,
    constraint UNQ_PROFILE_IMAGE_URL primary key (id, url)
);

create table member_outbox_history (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    id bigint not null,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table member_profiles (
    id bigint not null,
    version bigint,
    visit_count bigint not null,
    bio varchar(1000),
    goal varchar(1000),
    want varchar(1000),
    language_level varchar(255) check (language_level in ('BEGINNER','INTERMEDIATE','ADVANCED')),
    mbti varchar(255) check (mbti in ('ENFJ','ENFP','ENTJ','ENTP','ESFJ','ESFP','ESTJ','ESTP','INFJ','INFP','INTJ','INTP','ISFJ','ISFP','ISTJ','ISTP')),
    primary key (id)
);

create table member_suspend_history (
    is_released boolean,
    id bigint generated by default as identity,
    member_id bigint,
    release_at timestamp(6) with time zone,
    suspended_at timestamp(6) with time zone,
    reason varchar(255),
    primary key (id)
);

create table members (
    agreed_marketing_receive boolean not null,
    birth_day date,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    member_audit_id bigint unique,
    version bigint not null,
    handle varchar(20),
    country varchar(255),
    email varchar(255),
    fcm varchar(255),
    gender varchar(255) not null check (gender in ('MALE','FEMALE','SECRET')),
    image_url varchar(255),
    provider_display_name varchar(255),
    provider_id varchar(255),
    provider_type varchar(255) check (provider_type in ('GOOGLE','APPLE')),
    role varchar(255) check (role in ('MEMBER','PREMIUM','ADMIN')),
    status varchar(255) check (status in ('CREATED','ACTIVE','SUSPENDED','WITHDRAWN')),
    primary key (id),
    constraint UNQ_MEMBER_PROVIDER unique (provider_id, provider_type),
    constraint UNQ_MEMBER_EMAIL unique (email),
    constraint UNQ_MEMBER_HANDLE unique (handle)
);

create table notifications (
    is_read boolean not null,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    recipient_id bigint not null,
    body TEXT not null,
    data TEXT,
    title varchar(255) not null,
    type varchar(255) not null,
    primary key (id)
);

create table post_hashtags (
    hashtag_id bigint not null,
    id bigint generated by default as identity,
    post_id bigint not null,
    primary key (id),
    constraint UNQ_POST_HASHTAG unique (post_id, hashtag_id)
);

create table post_likes (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    member_id bigint not null,
    post_id bigint not null,
    primary key (id),
    constraint UNQ_POST_LIKE unique (post_id, member_id)
);

create table post_media (
    sequence integer not null,
    id bigint generated by default as identity,
    post_id bigint not null,
    type varchar(255) not null check (type in ('IMAGE','VIDEO')),
    url varchar(255) not null,
    primary key (id)
);

create table posts (
    blinded boolean not null,
    report_count integer not null,
    author_id bigint not null,
    blinded_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    like_count bigint not null,
    content TEXT not null,
    primary key (id)
);

create table relationship_event_outbox (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    failed_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table relationship_event_outbox_history (
    tries integer not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    id bigint not null,
    domain varchar(255),
    "key" varchar(255),
    payload TEXT,
    status varchar(255) check (status in ('PENDING','COMPLETE','FAILED')),
    topic varchar(255),
    primary key (id)
);

create table reports (
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    reported_user_id bigint not null,
    reporter_id bigint not null,
    reason TEXT,
    source_id varchar(255),
    source_type varchar(255) check (source_type in ('ECHO_POST','CHAT_USER')),
    trigger_message_id varchar(255),
    primary key (id)
);

create table wave_messages (
    created_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    sender_id bigint not null,
    wave_room_id bigint not null,
    content TEXT not null,
    primary key (id)
);

create table wave_rooms (
    max_participants integer not null,
    broadcaster_id bigint not null,
    ended_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    started_at timestamp(6) with time zone not null,
    title varchar(255) not null,
    primary key (id)
);

create index IDX_ATTACHMENT_SOURCE
   on attachments (source, source_id, status);

create index IDX_ATTACHMENT_UPLOADER
   on attachments (uploader_id, id);

create index IDX_ATTACHMENT_UNATTACHED
   on attachments (status, created_at);

create index IDX_CHAT_OUTBOX_DOMAIN
   on chat_event_outbox_history (domain);

create index IDX_ECHO_OUTBOX_DOMAIN
   on echo_event_outbox_history (domain);

create index IDX_MEMBER_OUTBOX_DOMAIN
   on member_outbox_history (domain);

create index IDX_MEMBER_SUSPEND_RELEASED
   on member_suspend_history (member_id, is_released);

create index IDX_NOTIFICATION_RECIPIENT
   on notifications (recipient_id, id desc);

create index IDX_RELATIONSHIP_OUTBOX_DOMAIN
   on relationship_event_outbox_history (domain);

create index IDX_REPORT_SOURCE
   on reports (source_type, id);

create index IDX_REPORT_REPORTED_USER
   on reports (reported_user_id, id);

create index IDX_REPORT_REPORTER
   on reports (reporter_id, id);

create index IDX_WAVE_MESSAGE_ROOM
   on wave_messages (wave_room_id, id);

alter table if exists member_profiles
   add constraint FKl6351gkifbovf4cecxhe224vq
   foreign key (id)
   references members;

alter table if exists members
   add constraint FK30hv5y9tu6ew97r9km37ya4al
   foreign key (member_audit_id)
   references member_audits;
