-- V2: 채팅 스키마
--
-- 채팅 데이터를 Mongo 에서 Postgres 로 옮기면서 추가한 테이블이다.
-- chat_event_outbox / chat_event_outbox_history 는 V1 에 이미 있으므로 여기서 만들지 않는다.

create table chat_rooms (
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    last_message_at timestamp(6) with time zone,
    last_message_preview varchar(200),
    primary key (id)
);

create table chat_room_members (
    id bigint generated by default as identity,
    last_read_at timestamp(6) with time zone,
    left_at timestamp(6) with time zone,
    member_id bigint not null,
    room_id bigint not null,
    primary key (id),
    constraint UNQ_CHAT_ROOM_MEMBER unique (room_id, member_id)
);

create table chat_messages (
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    room_id bigint not null,
    sender_id bigint not null,
    content TEXT,
    type varchar(255) check (type in ('TEXT','IMAGE','VIDEO','AUDIO')),
    primary key (id)
);

create table chat_message_files (
    sequence integer not null,
    id bigint generated by default as identity,
    message_id bigint not null,
    url varchar(1000) not null,
    primary key (id)
);

-- 메시지 커서 페이징은 (room_id, id desc) 로 훑는다. created_at 인덱스는 두지 않는다.
create index IDX_CHAT_MESSAGE_ROOM
   on chat_messages (room_id, id);

create index IDX_CHAT_ROOM_MEMBER_MEMBER
   on chat_room_members (member_id);

create index IDX_CHAT_MESSAGE_FILE_MESSAGE
   on chat_message_files (message_id, sequence);
